language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

# Linux
dist: xenial
sudo: required

# OS X only supports one image. Use the latest.
osx_image: xcode10.1

env:
  - TASK=check CONFIG_FLAGS="--enable-Werror --enable-test-Werror --enable-code-coverage"
  - TASK=distcheck

matrix:
  exclude:
    - os: osx
      compiler: gcc
      
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get install -y gcc-multilib lcov libasan* ;
        gem install coveralls-lcov;
    fi
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew uninstall libtool;
        brew install libtool;
        brew install lcov;
    fi
script:
  - export
  - autoreconf -iv
  - ./configure $CONFIG_FLAGS
  - make $TASK
after_success:
  - test "x$CC" = "xgcc" -o "x$CC" = "xclang" && make code-coverage-capture && coveralls-lcov asn1c-*-coverage.info
after_failure:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then find . -name test-suite.log -exec tail -v -n +1 {} + ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then find . -name test-suite.log -exec tail -n +1 {} + ; fi
